---
jobs:
- name: pull-status-check
  plan:
  - get: pull-request
    version: every
    trigger: true
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: build
    input_mapping:
      cg-site-source: pull-request
    file: pull-request/ci/build.yml
    on_success:
      put: pull-request
      params:
        path: pull-request
        status: success
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure

- name: deploy-production
  plan:
  - get: cg-site-source
    trigger: true
  - task: build
    file: cg-site-source/ci/build.yml
    params:
      COPY_OUTPUT: 1
  - put: old-docs-redirect
    params:
      manifest: cg-site-compiled/redirects/docs.cloud.gov/manifest.yml
      path: cg-site-compiled/redirects/docs.cloud.gov/
      current_app_name: docs
  - put: cloud-gov-production
    params:
      manifest: cg-site-compiled/manifest.yml
      path: cg-site-compiled
      current_app_name: landing
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy cg-site to Production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed cg-site to Production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}

resources:
- name: cg-site-source
  type: git
  source:
    uri: {{cg-site-git-url}}
    branch: {{cg-site-branch}}

- name: pull-request
  type: pull-request
  source:
    repo: {{cg-site-git-repo}}
    access_token: {{status-access-token}}
    every: true

- name: cloud-gov-production
  type: cf
  source:
    api: {{cf-api-url-production}}
    username: {{cf-deploy-username-production}}
    password: {{cf-deploy-password-production}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false

- name: old-docs-redirect
  type: cf
  source:
    api: {{cf-api-url-production}}
    username: {{cf-deploy-username-production}}
    password: {{cf-deploy-password-production}}
    organization: {{cf-organization}}
    space: {{cf-space-olddocs}}
    skip_cert_check: false

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
